### ISSUE TITLE
Error login app with Identity Toolkit

### ISSUE THREAD

**Issue by hue1992** [LazzyBee/LazyBee-Android#39]
Em đăng nhập google bằng  Identity Toolkit
nó bị lỗi Unrecoverable auth exception: Unknown

**Comment by vutamhoan** [comment]
Chắc nó cần config trên GAE, anh gán quyền cho em rồi. Vào xem cần add tham số gì thì add

**Comment by hue1992** [comment]
Em nhờ anh an Config rùi mà vẫn lỗi
