### ISSUE TITLE
bug UpdateCardFormServer

### ISSUE THREAD

**Issue by hue1992** [LazzyBee/LazyBee-Android#70]
Khi update card mà question ở clien(Có kí tự đặc biệt or đấu cách ) ko map với trên server

**Comment by vutamhoan** [comment]
Nếu không map được với server thì coi như không có vậy.
Hay là api sẽ bị lỗi????

**Comment by hue1992** [comment]
ở trên server đã được sửa rùi(Xóa bỏ kí tư đặc biệt) nên nó không tìm thấy cái Card ấy nữa

**Comment by vutamhoan** [comment]
Vậy em đồng bộ theo gid

**Comment by hue1992** [comment]
em cũng tính đến update theo gId nhưng trong có nhưng từ không có gId.
Em định xóa bỏ kí tự đặc biệt có đươc không anh?
